docker run -it -p 8020:8020 \
     -e DJANGO_SUPERUSER_USERNAME=<ADMIN NAME> \
     -e DJANGO_SUPERUSER_PASSWORD=<SUPER SECRET PASSWORD>  \
     -e DJANGO_SUPERUSER_EMAIL=<EMAIL> \
     <ADD IMAGE NAME>:<TAG> 
